### ISSUE TITLE
Issue running generator

### ISSUE THREAD

**Issue by andrewksmith** [aspnet-contrib/generator-aspnet-oauth#8]
Any tips as to where I should begin to look with the following error?

? 'Allo Andy! What would you like to do? Aspnet Oauth

Make sure you are in the directory you want to scaffold into.
This generator can also be run with: yo aspnet-oauth

? What is the name of the provider you want to create? xxxxpb03
? What is your name? xxxx3
? What is the Authorization Endpoint for this service? https://xxxx.com/auth
? What is the Token Endpoint for this service? https://xxxx.com/token
? What is the User Information Endpoint for this service? https://xxxx.com/info

```
 _-----_
|       |    .-----------------------.
|--(o)--|    |      Bye from us!     |
```

   `---------´   |       Chat soon.      |
    ( _´U`_ )    |      Yeoman team      |
    /**_A**_\    |    http://yeoman.io   |
     |  ~  |     '-----------------------'
   **'._**.'__
 ´   `|° ´ Y`

readline.js:924
            throw err;
            ^

TypeError: Cannot set property 'name' of undefined
    at null.<anonymous> (C:\Users\andy\AppData\Roaming\npm\node_modules\generator-aspnet-oauth\generators\app\index.js:48:30)
    at null.<anonymous> (C:\Users\andy\AppData\Roaming\npm\node_modules\generator-aspnet-oauth\node_modules\yeoman-generator\lib\base.js:226:7)
    at PromptUI.onCompletion (C:\Users\andy\AppData\Roaming\npm\node_modules\yo\node_modules\inquirer\lib\ui\prompt.js:57:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (C:\Users\andy\AppData\Roaming\npm\node_modules\yo\node_modules\rx-lite\rx.lite.js:1550:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\andy\AppData\Roaming\npm\node_modules\yo\node_modules\rx-lite\rx.lite.js:1489:14)
    at Subject.Rx.Subject.addProperties.onCompleted (C:\Users\andy\AppData\Roaming\npm\node_modules\yo\node_modules\rx-lite\rx.lite.js:5871:19)
    at Subject.tryCatcher (C:\Users\andy\AppData\Roaming\npm\node_modules\yo\node_modules\rx-lite\rx.lite.js:63:31)
    at AutoDetachObserverPrototype.completed (C:\Users\andy\AppData\Roaming\npm\node_modules\yo\node_modules\rx-lite\rx.lite.js:5796:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\andy\AppData\Roaming\npm\node_modules\yo\node_modules\rx-lite\rx.lite.js:1489:14)
    at AutoDetachObserver.tryCatcher (C:\Users\andy\AppData\Roaming\npm\node_modules\yo\node_modules\rx-lite\rx.lite.js:63:31)

**Comment by kevinchalet** [comment]
Thanks for reporting this issue!

I'll ping @jerriep and see how we can fix it.

**Comment by jerriep** [comment]
@andrewksmith I published a new version to NPM. Please update using

```
npm install -g generator-aspnet-oauth
```

**Comment by andrewksmith** [comment]
Fixed.  Thanks

**Comment by kevinchalet** [comment]
:clap: :clap: for @jerriep
